http://localhost:4000/


###
http://localhost:3000/blocks

###
http://localhost:4000/status

###
POST http://localhost:3000/blocks

{
    "message" : "New block"
}

###
http://localhost:4000/blocks/4

###
http://localhost:4000/balance/9f33705ffdf7aebbfdad4a975e8b61c0142ef28df4e187313de07fb135dfd1c7db2eb2c4dda9ec8ce381e5e75af2e01b8d9420a8d14432b02edc8b51b7108610

###
http://localhost:4000/mempool

###
POST http://localhost:4000/transactions 

{
    "to": "jungyoon",
    "amount": 50
}

###
POST http://localhost:4000/peers

{
    "address": "127.0.0.1",
    "port": "3000"
}

###
http://localhost:4000/peers